#!/usr/bin/env bash
# ==============================================================================
#               BUG.x Environment Activation Script
# ==============================================================================
#
# -- INFO --
# 1. This script is auto-generated by setup.sh.
# 2. It prepends the project's binary directory to your PATH.
# 3. It sets a guard to ensure tools are run from within the project folder.
#
# ==============================================================================

# Guard: Ensure the script is sourced from within the project directory.
if [[ "$PWD" != "$HOME/BUGx"* ]]; then
    echo -e "\033[1;31m[ERROR]\033[0m Lingkungan BUG.x hanya boleh diaktifkan dari dalam direktori ~/BUGx."
    return 1
fi

export PATH="$HOME/BUGx/bin:$PATH"
export BUGX_ACTIVE=1

echo -e "\033[1;32m[OK]\033[0m Lingkungan BUG.x telah diaktifkan."
echo -e "     Semua tools di ~/BUGx/bin sekarang ada di PATH Anda."

# Simple deactivate function
deactivate() {
    export PATH=$(echo "$PATH" | sed -e "s|$HOME/BUGx/bin:||")
    unset BUGX_ACTIVE
    unset -f deactivate
    echo -e "\033[1;33m[WARN]\033[0m Lingkungan BUG.x telah dinonaktifkan."
}
